apiVersion: apps/v1
kind: Deployment
metadata:
  name: miweb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miweb
  template:
    metadata:
      labels:
        app: miweb
    spec:
      containers:
        - name: miweb
          image: jrodriguezferrer0/miweb:latest
          ports:
            - containerPort: 8080
