apiVersion: v1
kind: Service
metadata:
  name: miweb-service 
spec:
  type: NodePort
  selector:
    app: miweb 
  ports:
    - port: 8080 # Puerto l√≥gico del servicio
      targetPort: 8080 #Puerto del contenedor
      nodePort: 30080 #Puerto del nodo (para acceder desde fuera)